### ISSUE TITLE
broken npm installation

### ISSUE THREAD

**Issue by inakianduaga** [AutoScout24/toguru-panel#1]
`npm install` on a fresh repo clone fails (both using mac and node 7 dockerized)

```sh
docker run -v $PWD:/app -w /app node:7 npm install
```

returns

```
npm ERR! cb() never called!
```

**Comment by inakianduaga** [comment]
Found it, `gulp-uglifycss": "1.0.7"` breaks the build
https://github.com/npm/npm/issues/16174#issuecomment-289770391

good that it was only a patch semver upgrade...

**Comment by ArchDev** [comment]
Thanks, merged your pull request that fix it.
