### ISSUE TITLE
Missing metadata.yaml file in repository

### ISSUE THREAD

**Issue by teo-scout24** [AutoScout24/toguru-panel#6]
Hi maintainers,

Greatly appreciate if you can help to add a metadata.yaml file into this repo as git-secrets alert is triggering OpsGenie alert that goes to Engineering Managers at the moment.

By having a proper metadata.yaml, the git-secrets alert will send an email to your team instead of triggering OpsGenie alert. For more information about the metadata.yaml format, you can refer to the link below. Thanks!

https://github.com/AutoScout24/repo-metadata-reporter

**Comment by omakoleg** [comment]
It is public repository. 
Do we really need to expose internal tools configuration ?

**Comment by teo-scout24** [comment]
Oh, just noticed this is a public repo. Probably will default public repo email alert default to security team since we trigger OpsGenie regardless if there's metadata.yaml. Thanks
